spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.175.210:3306/apple?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: prod
    password: jkdfjalksdjflaJLJFJljjdfa!@@#hdfjh%$#^&j3241324
#    url: jdbc:mysql://127.0.0.1:3306/apple?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#    username: root
#    password: password
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 6000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 6000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter: stat,wall,log4j
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


#热部署
#  devtools:
#    restart:
#      enabled: true  #热部署开启
#      additional-paths: src/main/java   #重启范围

qiNiu:
  accessKey: dduN5ZJGm0AcMz3OWShkTRBk8QqlsfKInR3CBuBz
  accessKeySecret: VH3NxSjPw5VOjYq_xCkuab59Gl5aBp95s2yL-EHU
  bucketName: zz
  url: http://pv312drsw.bkt.clouddn.com/


#我的appid
#weChat:
#  appId: wxe1a48f73244684be
#  secret: f7ee23b40c112fd2a296ecc95b0589a5

#线上的
weChat:
  appId: wx5c49cc26ae59968c
  secret: 351c9b805391f5c32b9ddac785009dcd

#mybatis配置

mybatis:
  type-aliases-package: com.nplat.convert.entity
  configuration:
    map-underscore-to-camel-case: true

